{{- if .Values.awsstore }}
{{- if .Values.awsstore.useAwsStore }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "cost-analyzer.fullname" . }}-awsstore
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cost-analyzer.commonLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: awsstore
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: awsstore
      {{- with .Values.global.podAnnotations}}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: awsstore-serviceaccount
      {{- if .Values.awsstore.priorityClassName }}
      priorityClassName: "{{ .Values.awsstore.priorityClassName }}"
      {{- end }}
      {{- with .Values.awsstore.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - image: {{ .Values.awsstore.imageNameAndVersion }}
          name: awsstore
          # Just sleep forever
          command: [ "sleep" ]
          args: [ "infinity" ]
{{- end }}
{{- end }}
