apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  labels:
    {{ include "cost-analyzer.commonLabels" . | nindent 4 }}
data:
  nginx.conf: |
    gzip_static  on;

    upstream api {
        server {{ template "cost-analyzer.fullname" . }}.{{ .Release.Namespace }}:9001;
    }

    upstream model {
        server {{ template "cost-analyzer.fullname" . }}.{{ .Release.Namespace }}:9003;
    }

{{- if .Values.global.grafana.proxy }}
    upstream grafana {
{{- if .Values.global.grafana.enabled }}
        server {{ .Release.Name }}-grafana.{{ .Release.Namespace }};
{{ else }}
        server {{.Values.global.grafana.domainName}};
{{ end }}
    }
{{ end }}

    server {
        listen 9090;
        server_name _;
        root /var/www;
        index index.html;
        add_header Cache-Control "no-cache";
        add_header ETag "{{ $.Chart.Version }}";
        location /api/ {
            proxy_pass http://api/;
            proxy_redirect off;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_set_header  X-Real-IP  $remote_addr;
            proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
        }
        location /model/ {       	
            proxy_connect_timeout       180;
            proxy_send_timeout          180;
            proxy_read_timeout          180;
            proxy_pass http://model/;
            proxy_redirect off;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_set_header  X-Real-IP  $remote_addr;
            proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
        }
{{- if .Values.global.grafana.proxy }}
        location /grafana/ {
            proxy_pass http://grafana/;
            proxy_redirect off;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_set_header  X-Real-IP  $remote_addr;
            proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
        }
{{ end }}
    }
