apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name:  cost-analyzer
  namespace: monitoring
  labels:
    app:  cost-analyzer
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  cost-analyzer
    spec:
      restartPolicy: Always
      serviceAccountName: cost-analyzer
      containers:
      - image: ajaytripathy/kubecost:latest
        name:  cost-analyzer-server
        resources:
          requests:
            cpu: "20m"
            memory: "55M"
        #livenessProbe:
        #  httpGet:
        #    path: /_status/healthz
        #    port: 5000
        #  initialDelaySeconds: 90
        #  timeoutSeconds: 10
        #readinessProbe:
        #  httpGet:
        #    path: /_status/healthz
        #    port: 5000
        #  initialDelaySeconds: 30
        #  timeoutSeconds: 10
        imagePullPolicy: Always
      imagePullSecrets:
        - name: regcred
      
      