{{- if .Values.kubecostProductConfigs -}}
{{- if .Values.kubecostProductConfigs.metricsConfigs -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ default "metrics-config" .Values.metricsConfigmapName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "cost-analyzer.commonLabels" . | nindent 4 }}
data:
  metrics.json: '{{ toJson .Values.kubecostProductConfigs.metricsConfigs }}'
{{- end -}}
{{- end -}}