{{- if .Values.kubecostProductConfigs }}
{{- if .Values.kubecostProductConfigs.cloudAccountMapping }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "account-mapping"
  namespace: {{ .Release.Namespace }}
  labels: {{ include "cost-analyzer.commonLabels" . | nindent 4 }}
data:
  account-map.json: '{{ toJson .Values.kubecostProductConfigs.cloudAccountMapping }}'
{{- end }}
{{- end }}