{{- if .Values.remoteWrite -}}
{{- if .Values.remoteWrite.postgres -}}
{{- if .Values.remoteWrite.postgres.enabled -}}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "cost-analyzer.fullname" . }}-postgres
  labels:
    {{ include "cost-analyzer.commonLabels" . | nindent 4 }}
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: postgres
    spec:
        containers:
            - image: timescale/pg_prometheus:latest
              name: pgprometheus
              ports:
              - containerPort: 5432
              args:
                - -csynchronous_commit=off
              env:
                - name: POSTGRES_PASSWORD
                  value: {{ .Values.remoteWrite.postgres.auth.password }}
                - name: POSTGRES_USER
                  value: postgres
              volumeMounts:
                - mountPath: /var/lib/postgresql/data
                  name: postgres-pv-volume
                  subPath: postgres
        volumes:
          - name: postgres-pv-volume
            persistentVolumeClaim:
              claimName: postgres-pv-claim
{{- end }}
{{- end }}
{{- end }}