kind: Service
apiVersion: v1
metadata:
  name: pgprometheus-adapter
  labels:
    {{ include "cost-analyzer.commonLabels" . | nindent 4 }}
spec:
  selector:
    app: adapter
  type: ClusterIP
  ports:
    - name: server
      port: 9201
      targetPort: 9201